spring.application.name=onePlusOne

spring.datasource.url=jdbc:mysql://localhost:3306/one_plus_one
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

jwt.secret.key=${JWT_SECRET_KEY}
Kakao.api-key=${KAKAO_API_KEY}
